const pool=require('../config/dbPool');
const MAX_LOGS=10000;
function addAuditLog(entry={}){const log={id:`audit-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,cafeId:String(entry.cafeId||'cafe-1'),user:String(entry.user||'System'),userId:String(entry.userId||''),role:String(entry.role||'System'),action:String(entry.action||'System Activity'),category:String(entry.category||'System'),details:String(entry.details||''),entityId:String(entry.entityId||''),source:String(entry.source||'Server'),method:String(entry.method||''),path:String(entry.path||''),ip:String(entry.ip||''),statusCode:Number(entry.statusCode||0),success:entry.success!==false,durationMs:Number(entry.durationMs||0),createdAt:entry.createdAt||new Date().toISOString()};
  // Keep request completion fast; insert asynchronously. user_id is only set when numeric.
  const uid=/^\d+$/.test(log.userId)?Number(log.userId):null;
  pool.execute(`INSERT INTO audit_logs (external_audit_id,cafe_id,user_id,user_name_snapshot,username_snapshot,role_snapshot,action,category,details,entity_id,source,http_method,request_path,ip_address,status_code,success,duration_ms,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[log.id,log.cafeId,uid,log.user,log.userId||null,log.role,log.action,log.category,log.details,log.entityId||null,log.source,log.method||null,log.path||null,log.ip||null,log.statusCode||null,log.success?1:0,log.durationMs||null,new Date(log.createdAt)]).catch(e=>console.error('Audit DB insert error:',e.message));
  return log;
}
async function listAuditLogs({cafeId='cafe-1',limit=1000}={}){const safe=Math.min(Math.max(Number(limit)||1000,1),MAX_LOGS);const [rows]=await pool.query(`SELECT * FROM audit_logs WHERE cafe_id=? ORDER BY created_at DESC LIMIT ${safe}`,[String(cafeId)]);return rows.map(r=>({id:r.external_audit_id||String(r.audit_id),cafeId:r.cafe_id,user:r.user_name_snapshot||r.username_snapshot||'System',userId:r.user_id?String(r.user_id):(r.username_snapshot||''),role:r.role_snapshot||'System',action:r.action,category:r.category||'System',details:r.details||'',entityId:r.entity_id||'',source:r.source||'Server',method:r.http_method||'',path:r.request_path||'',ip:r.ip_address||'',statusCode:Number(r.status_code||0),success:Boolean(r.success),durationMs:Number(r.duration_ms||0),createdAt:new Date(r.created_at).toISOString()}));}
async function clearAuditLogs({cafeId='cafe-1'}={}){await pool.execute('DELETE FROM audit_logs WHERE cafe_id=?',[String(cafeId)]);return true;}
module.exports={addAuditLog,listAuditLogs,clearAuditLogs};
