"use strict";
const pool=require('../config/dbPool');
function cleanText(v,fallback=''){return String(v??fallback).trim();}
function normalizeArray(v){if(Array.isArray(v))return v.map(x=>cleanText(x)).filter(Boolean);if(!v)return [];return String(v).split(',').map(x=>x.trim()).filter(Boolean);}
function normalizePromotion(input={},existing={}){const id=cleanText(input.id||existing.id||`promo-${Date.now()}-${Math.random().toString(36).slice(2,7)}`);const now=new Date().toISOString();return {id,cafeId:cleanText(input.cafeId||existing.cafeId||'cafe-1')||'cafe-1',name:cleanText(input.name??existing.name??'Promotion'),description:cleanText(input.description??existing.description??''),type:cleanText(input.type??existing.type??'percentage').toLowerCase()==='fixed'?'fixed':'percentage',value:Math.max(0,Number(input.value??existing.value??0)||0),scope:['all','category','products'].includes(cleanText(input.scope??existing.scope).toLowerCase())?cleanText(input.scope??existing.scope).toLowerCase():'all',categories:normalizeArray(input.categories??existing.categories),productNames:normalizeArray(input.productNames??existing.productNames),eligibility:(normalizeArray(input.eligibility??existing.eligibility).map(x=>x.toLowerCase()).length?normalizeArray(input.eligibility??existing.eligibility).map(x=>x.toLowerCase()):['all']),minimumSubtotal:Math.max(0,Number(input.minimumSubtotal??existing.minimumSubtotal??0)||0),startDate:cleanText(input.startDate??existing.startDate??''),endDate:cleanText(input.endDate??existing.endDate??''),startTime:cleanText(input.startTime??existing.startTime??''),endTime:cleanText(input.endTime??existing.endTime??''),weekdays:normalizeArray(input.weekdays??existing.weekdays).map(x=>x.toLowerCase()),active:input.active===undefined?(existing.active===undefined?true:Boolean(existing.active)):Boolean(input.active),createdAt:existing.createdAt||now,updatedAt:now};}
function dateText(v){if(!v)return '';if(typeof v==='string')return v.slice(0,10);return new Date(v).toISOString().slice(0,10);}
function timeText(v){if(!v)return '';return String(v).slice(0,8);}
async function list(cafeId){const id=cleanText(cafeId||'cafe-1')||'cafe-1';const [rows]=await pool.execute('SELECT * FROM promotions WHERE cafe_id=? ORDER BY updated_at DESC',[id]);const out=[];for(const r of rows){const [cats]=await pool.execute(`SELECT c.category_name FROM promotion_categories pc JOIN categories c ON c.category_id=pc.category_id WHERE pc.promotion_id=?`,[r.promotion_id]);const [prods]=await pool.execute(`SELECT p.product_name FROM promotion_products pp JOIN products p ON p.product_id=pp.product_id WHERE pp.promotion_id=?`,[r.promotion_id]);const [elig]=await pool.execute('SELECT eligibility FROM promotion_eligibilities WHERE promotion_id=?',[r.promotion_id]);const [days]=await pool.execute('SELECT weekday FROM promotion_weekdays WHERE promotion_id=?',[r.promotion_id]);out.push({id:r.promotion_id,cafeId:r.cafe_id,name:r.promotion_name,description:r.description||'',type:r.discount_type==='Fixed'?'fixed':'percentage',value:Number(r.discount_value||0),scope:String(r.scope_type||'All').toLowerCase(),categories:cats.map(x=>x.category_name),productNames:prods.map(x=>x.product_name),eligibility:elig.length?elig.map(x=>String(x.eligibility).toLowerCase()):['all'],minimumSubtotal:Number(r.minimum_subtotal||0),startDate:dateText(r.start_date),endDate:dateText(r.end_date),startTime:timeText(r.start_time),endTime:timeText(r.end_time),weekdays:days.map(x=>String(x.weekday).toLowerCase()),active:Boolean(r.is_active),createdAt:new Date(r.created_at).toISOString(),updatedAt:new Date(r.updated_at).toISOString()});}return out;}
async function upsert(input){const existing=(input.id?(await list(input.cafeId||'cafe-1')).find(x=>String(x.id)===String(input.id)):null)||{};const row=normalizePromotion(input,existing);const conn=await pool.getConnection();try{await conn.beginTransaction();await conn.execute(`INSERT INTO promotions (promotion_id,cafe_id,promotion_name,description,discount_type,discount_value,scope_type,minimum_subtotal,start_date,end_date,start_time,end_time,is_active) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE promotion_name=VALUES(promotion_name),description=VALUES(description),discount_type=VALUES(discount_type),discount_value=VALUES(discount_value),scope_type=VALUES(scope_type),minimum_subtotal=VALUES(minimum_subtotal),start_date=VALUES(start_date),end_date=VALUES(end_date),start_time=VALUES(start_time),end_time=VALUES(end_time),is_active=VALUES(is_active),updated_at=CURRENT_TIMESTAMP`,[row.id,row.cafeId,row.name,row.description,row.type==='fixed'?'Fixed':'Percentage',row.value,row.scope==='category'?'Category':row.scope==='products'?'Products':'All',row.minimumSubtotal,row.startDate||null,row.endDate||null,row.startTime||null,row.endTime||null,row.active?1:0]);
await conn.execute('DELETE FROM promotion_categories WHERE promotion_id=?',[row.id]);await conn.execute('DELETE FROM promotion_products WHERE promotion_id=?',[row.id]);await conn.execute('DELETE FROM promotion_eligibilities WHERE promotion_id=?',[row.id]);await conn.execute('DELETE FROM promotion_weekdays WHERE promotion_id=?',[row.id]);
if(row.scope==='category')for(const name of row.categories){const [cats]=await conn.execute('SELECT category_id FROM categories WHERE cafe_id=? AND (category_name=? OR canonical_key=?) LIMIT 1',[row.cafeId,name,name.toLowerCase()]);if(cats.length)await conn.execute('INSERT IGNORE INTO promotion_categories (promotion_id,category_id) VALUES (?,?)',[row.id,cats[0].category_id]);}
if(row.scope==='products')for(const name of row.productNames){const [ps]=await conn.execute('SELECT product_id FROM products WHERE cafe_id=? AND product_name=? LIMIT 1',[row.cafeId,name]);if(ps.length)await conn.execute('INSERT IGNORE INTO promotion_products (promotion_id,product_id) VALUES (?,?)',[row.id,ps[0].product_id]);}
for(const e0 of row.eligibility){const m={all:'All',general:'General',student:'Student',senior:'Senior',pwd:'PWD'};const e=m[e0]||'All';await conn.execute('INSERT IGNORE INTO promotion_eligibilities (promotion_id,eligibility) VALUES (?,?)',[row.id,e]);}
for(const d0 of row.weekdays){const m={mon:'Mon',monday:'Mon',tue:'Tue',tuesday:'Tue',wed:'Wed',wednesday:'Wed',thu:'Thu',thursday:'Thu',fri:'Fri',friday:'Fri',sat:'Sat',saturday:'Sat',sun:'Sun',sunday:'Sun'};if(m[d0])await conn.execute('INSERT IGNORE INTO promotion_weekdays (promotion_id,weekday) VALUES (?,?)',[row.id,m[d0]]);}
await conn.commit();return (await list(row.cafeId)).find(x=>x.id===row.id)||row;}catch(e){await conn.rollback();throw e;}finally{conn.release();}}
async function remove(id,cafeId){const [r]=await pool.execute('DELETE FROM promotions WHERE promotion_id=? AND cafe_id=?',[String(id),String(cafeId||'cafe-1')]);return r.affectedRows>0;}
module.exports={list,upsert,remove,normalizePromotion};
