<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CafeKiosk - Settings</title><link rel="stylesheet" href="../Assets/css/admin-extension.css">
  <link rel="stylesheet" href="../Assets/css/kiosk-access.css?v=1"><script src="../Assets/js/auth-session.js"></script>  <link rel="stylesheet" href="../Assets/css/uniform-theme.css?v=33">
  <link rel="stylesheet" href="../Assets/css/profile-menu.css?v=30">
  <link rel="stylesheet" href="/Assets/css/message-dialog.css?v=1">
</head><body class="ck-admin-page uniform-admin"><div class="ck-shell"><aside class="ck-sidebar"><a class="ck-brand" href="/Admin/dashboard.php"><img src="../Assets/images/logo.png" alt="CafeKiosk"></a><div class="ck-side-label">ADMIN</div><nav class="ck-nav">
<a href="/Admin/dashboard.php"><span class="ico">▦</span><span class="label">Dashboard</span></a>
<a href="/admin/order-monitor"><span class="ico">🛒</span><span class="label">Order</span></a>
<a href="/Admin/menu-management.php"><span class="ico">▤</span><span class="label">Menu Management</span></a>
<a href="/Admin/promotions-discount.php" class=""><span class="ico">%</span><span class="label">Promotions & Discount</span></a>
<a href="/Admin/inventory.php"><span class="ico">□</span><span class="label">Inventory</span></a>
<a href="/Admin/report.php"><span class="ico">▥</span><span class="label">Report</span></a>
<a href="/Admin/audit-logs.php"><span class="ico">▣</span><span class="label">Audit Logs</span></a>
<a href="/Admin/user.php" class=""><span class="ico">●</span><span class="label">User</span></a>
<a href="/Admin/settings.php" class="active"><span class="ico">⚙</span><span class="label">Settings</span></a>
</nav></aside><main class="ck-main"><div class="ck-topbar"><div class="ck-title"><h1>Admin Settings Monitor</h1></div><div class="ck-profile"><span>● &nbsp;<span id="adminName">Administrator</span></span><span>⌄</span></div></div><section class="ck-card"><h2>System Settings</h2><div class="ck-grid"><div class="ck-card"><div class="ck-toolbar"><div><strong>💳 &nbsp; Payment Method</strong><div class="ck-muted">Configure payment options available to POS and Kiosk.</div></div><button class="ck-btn primary" data-setting="payment">Configure</button></div></div><div class="ck-card"><div class="ck-toolbar"><div><strong>🏪 &nbsp; Store Information</strong><div class="ck-muted">Business name, address, contact information and operating hours.</div></div><button class="ck-btn primary" data-setting="store">Manage</button></div></div><div class="ck-card"><div class="ck-toolbar"><div><strong>％ &nbsp; Tax & Service Charges</strong><div class="ck-muted">Set tax rates and service charges for orders.</div></div><button class="ck-btn primary" data-setting="tax">Configure</button></div></div><div class="ck-card"><div class="ck-toolbar"><div><strong>⚙ &nbsp; System Preferences</strong><div class="ck-muted">Customize system preferences and defaults.</div></div><button class="ck-btn primary" data-setting="preferences">Manage</button></div></div><div class="ck-card"><div class="ck-toolbar"><div><strong>☕ &nbsp; Kiosk Access</strong><div class="ck-muted">Manage this cafe's unique Kiosk link and branded QR code.</div></div><button class="ck-btn primary" data-setting="kiosk">Manage</button></div></div></div></section></main></div><div class="ck-modal" id="settingsModal"><div class="ck-dialog" style="max-width:620px"><div class="ck-toolbar"><h2 id="settingsTitle">Settings</h2><button class="ck-btn" id="closeSettings">Close</button></div><div id="settingsBody"></div></div></div><script src="../Assets/js/kiosk-qr.js?v=1"></script>
  <script src="../Assets/js/settings-page.js?v=3"></script>  <script src="../Assets/js/uniform-theme.js?v=33"></script>
  <script src="../Assets/js/profile-menu.js?v=31"></script>
  <script src="/Assets/js/message-dialog.js?v=1"></script>
</body></html>
